# Generated by Django 5.1.1 on 2024-11-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_options_book_description_book_edition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='bookissue',
            options={'ordering': ['-issue_date'], 'verbose_name': 'Book Issue', 'verbose_name_plural': 'Book Issues'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name'], 'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('BUSINESS', 'BUSINESS: 5'), ('SCIENCE', 'SCIENCE: 5'), ('COMPUTER', 'COMPUTER: 5'), ('MATHEMATICS', 'MATHEMATICS: 5'), ('PHYSICS', 'PHYSICS: 5'), ('CHEMISTRY', 'CHEMISTRY: 5'), ('BIOLOGY', 'BIOLOGY: 5'), ('ECONOMICS', 'ECONOMICS: 5'), ('MANAGEMENT', 'MANAGEMENT: 5'), ('MARKETING', 'MARKETING: 5'), ('FINANCE', 'FINANCE: 5'), ('LITERATURE', 'LITERATURE: 5'), ('HISTORY', 'HISTORY: 5'), ('PHILOSOPHY', 'PHILOSOPHY: 5')], max_length=20),
        ),
    ]
